### ISSUE TITLE
treasures still broken

### ISSUE THREAD

**Issue by SwartzCr** [SwartzCr/nekoatsume#35]
[Main Menu] Choose an action! check treasures
Traceback (most recent call last):
  File "./nekoatsume.py", line 6, in <module>
    display.main()
  File "/home/swartzcr/Documents/coding/nekoatsume/lib/display.py", line 200, in main
    actions[inp](data)
  File "/home/swartzcr/Documents/coding/nekoatsume/lib/display.py", line 105, in check_treasures
    for cat in [cat for cat in data["cats"] if cat["given_treasure"]]:
TypeError: string indices must be integers

**Comment by SwartzCr** [comment]
fixed in #33
